version: "3.7"
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: almighty_local_django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.local
    depends_on:
      - mariadb
    command: >
      bash -c "python manage.py migrate --settings=almighty_reading.settings.local &&
               python manage.py runserver 0.0.0.0:8000 --settings=almighty_reading.settings.local"

  mariadb:
    image: mariadb:10.5
    restart: always
    container_name: almighty_local_mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: yourpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - maria-data:/var/lib/mysql

volumes:
  maria-data:
