# Generated by Django 4.0.3 on 2022-04-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_created=True, null=True)),
                ('app_version', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
