# Generated by Django 4.0.3 on 2022-04-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_value', '0003_appversion_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='down_file',
            field=models.FileField(null=True, upload_to='app_version_down_file'),
        ),
    ]
