# Generated by Django 4.0.3 on 2022-04-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_value', '0005_alter_appversion_down_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='down_file',
            field=models.FileField(blank=True, null=True, upload_to='AppVersion_down_file'),
        ),
    ]
