# Generated by Django 4.0.3 on 2022-04-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_value', '0006_alter_appversion_down_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appversion',
            name='down_file',
        ),
    ]
