# Generated by Django 4.0.4 on 2022-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_value', '0007_remove_appversion_down_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtcValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etc_name', models.CharField(blank=True, max_length=50, null=True)),
                ('etc_value', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
