# Generated by Django 4.0.4 on 2022-05-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_value', '0008_etcvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.IntegerField(blank=True, max_length=3, null=True)),
                ('plan_idx', models.IntegerField(blank=True, max_length=3, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_code', models.IntegerField(default=0, max_length=2)),
                ('app_idx', models.IntegerField(default=0, max_length=2)),
                ('step_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
