# Generated by Django 4.0.4 on 2022-05-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_info', '0011_alter_studymember_plan_code_and_more'),
        ('common_value', '0009_plan_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
