# Generated by Django 4.0.4 on 2022-05-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_value', '0010_delete_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncode',
            name='mcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commoncode',
            name='ord',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='app_idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_code',
            field=models.IntegerField(default=0),
        ),
    ]
