# Generated by Django 4.0.4 on 2022-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_value', '0011_alter_commoncode_mcode_alter_commoncode_ord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_code', models.IntegerField(default=0)),
                ('app_idx', models.IntegerField(default=0)),
                ('step_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
