# Generated by Django 4.0.3 on 2022-04-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, null=True)),
                ('btype', models.CharField(max_length=20, null=True)),
                ('ctype', models.CharField(max_length=20, null=True)),
                ('cname', models.CharField(max_length=255, null=True)),
                ('ukey', models.IntegerField(max_length=10, null=True)),
                ('uname', models.CharField(max_length=32, null=True)),
                ('pkey', models.IntegerField(max_length=10, null=True)),
                ('pname', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcode', models.IntegerField(max_length=10, null=True)),
                ('acode', models.CharField(max_length=6, null=True)),
                ('mname', models.CharField(max_length=10, null=True)),
                ('webid', models.CharField(max_length=20, null=True)),
                ('mkind', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
