# Generated by Django 4.0.3 on 2022-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acode', models.CharField(max_length=10, null=True)),
                ('aname', models.CharField(max_length=30, null=True)),
                ('aman', models.CharField(max_length=10, null=True)),
                ('webid', models.CharField(max_length=10, null=True)),
                ('wcode', models.CharField(max_length=10, null=True)),
                ('akind', models.CharField(max_length=10, null=True)),
                ('bonbuacode', models.CharField(max_length=10, null=True)),
                ('analkind', models.CharField(max_length=10, null=True)),
                ('busikind', models.CharField(max_length=10, null=True)),
                ('typekind', models.CharField(max_length=10, null=True)),
                ('zonekind', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
