# Generated by Django 4.0.3 on 2022-04-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_info', '0002_testagency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcode', models.CharField(max_length=10, null=True)),
                ('mname', models.CharField(max_length=10, null=True)),
                ('mtype', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
