# Generated by Django 4.0.3 on 2022-04-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_info', '0003_testmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmember',
            name='acode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
