# Generated by Django 4.0.3 on 2022-05-02 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_memberlevelmanage_level_code'),
        ('library', '0007_alter_level_level_code_alter_level_level_name'),
        ('member_info', '0004_testmember_acode'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmember',
            name='level_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='library.level'),
        ),
        migrations.AddField(
            model_name='testmember',
            name='plan_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.plan'),
        ),
    ]
