# Generated by Django 4.0.3 on 2022-05-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_info', '0005_testmember_level_code_testmember_plan_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAgency',
        ),
        migrations.DeleteModel(
            name='ZCenter',
        ),
        migrations.DeleteModel(
            name='ZMember',
        ),
    ]
