# Generated by Django 4.0.3 on 2022-05-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_membertopiclog_stage_membertopiclog_step_plan_stage1_and_more'),
        ('library', '0007_alter_level_level_code_alter_level_level_name'),
        ('member_info', '0006_delete_testagency_delete_zcenter_delete_zmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcode', models.CharField(max_length=10, null=True)),
                ('mname', models.CharField(max_length=10, null=True)),
                ('mtype', models.CharField(max_length=10, null=True)),
                ('acode', models.CharField(max_length=10, null=True)),
                ('level_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='library.level')),
                ('plan_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.plan')),
            ],
        ),
    ]
