# Generated by Django 4.0.4 on 2022-05-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_info', '0007_studymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymember',
            name='current_study',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studymember',
            name='mcode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studymember',
            name='mname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
