# Generated by Django 4.0.4 on 2022-05-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_info', '0012_alter_studymember_plan_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymember',
            name='current_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
