# Generated by Django 4.0.4 on 2022-06-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_info', '0014_alter_studymember_acode_alter_testmember_acode'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymember',
            name='list_enable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
