# Generated by Django 4.0.4 on 2022-06-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_info', '0015_studymember_list_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymember',
            name='level_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studymember',
            name='plan_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
