# Generated by Django 4.0.4 on 2022-06-30 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0010_rename_is_show_level_show_level'),
        ('manager', '0018_plan_seq'),
        ('member_info', '0016_alter_studymember_level_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymember',
            name='level_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='library.level'),
        ),
        migrations.AlterField(
            model_name='studymember',
            name='plan_code',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.plan'),
        ),
    ]
