# Generated by Django 4.0.4 on 2022-07-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_info', '0017_alter_studymember_level_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymember',
            name='is_check',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
