# Generated by Django 4.0.3 on 2022-04-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0002_alter_steplog_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StepLog',
        ),
    ]
