# Generated by Django 4.0.3 on 2022-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0004_stepfinishlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('topic_code', models.CharField(blank=True, max_length=10, null=True)),
                ('step_code', models.CharField(blank=True, max_length=10, null=True)),
                ('study_time', models.CharField(blank=True, max_length=25, null=True)),
                ('step_dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
