# Generated by Django 4.0.3 on 2022-05-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0005_steptimelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiclog',
            name='end_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topiclog',
            name='start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
