# Generated by Django 4.0.3 on 2022-05-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0006_topiclog_end_dt_topiclog_start_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepfinishlog',
            name='stage',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='stepfinishlog',
            name='step',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
