# Generated by Django 4.0.3 on 2022-05-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0007_stepfinishlog_stage_stepfinishlog_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepfinishlog',
            name='dt_day',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='stepfinishlog',
            name='dt_month',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='stepfinishlog',
            name='dt_year',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
