# Generated by Django 4.0.4 on 2022-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0008_stepfinishlog_dt_day_stepfinishlog_dt_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepfinishlog',
            name='plan_type',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stepfinishlog',
            name='study_code',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
