# Generated by Django 4.0.4 on 2022-05-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0009_stepfinishlog_plan_type_stepfinishlog_study_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepfinishlog',
            name='mi_test',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
    ]
