# Generated by Django 4.0.4 on 2022-05-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0010_stepfinishlog_mi_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepfinishlog',
            name='mi_test',
        ),
    ]
