# Generated by Django 4.0.4 on 2022-05-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0011_remove_stepfinishlog_mi_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicLog',
        ),
    ]
