# Generated by Django 4.0.4 on 2022-05-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0012_delete_topiclog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepfinishlog',
            name='c_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stepfinishlog',
            name='plan_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stepfinishlog',
            name='stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stepfinishlog',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stepfinishlog',
            name='study_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stepfinishlog',
            name='t_point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
