# Generated by Django 4.0.4 on 2022-06-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0013_alter_stepfinishlog_c_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepfinishlog',
            name='finish_today',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
