# Generated by Django 4.0.4 on 2022-06-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_info', '0014_stepfinishlog_finish_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepfinishlog',
            name='step_num',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
