# Generated by Django 4.0.3 on 2022-04-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLevelManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('level_code', models.IntegerField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPlanManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('plan_code', models.IntegerField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.IntegerField(blank=True, max_length=3, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
