# Generated by Django 4.0.3 on 2022-05-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberplanmanage',
            name='plan_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.plan'),
        ),
    ]
