# Generated by Django 4.0.3 on 2022-05-02 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_theme'),
        ('manager', '0002_alter_memberplanmanage_plan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlevelmanage',
            name='level_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='library.level'),
        ),
    ]
