# Generated by Django 4.0.3 on 2022-05-02 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0007_alter_level_level_code_alter_level_level_name'),
        ('manager', '0005_alter_memberlevelmanage_level_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlevelmanage',
            name='level_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='library.level'),
        ),
    ]
