# Generated by Django 4.0.3 on 2022-05-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_membertopiclog_end_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertopiclog',
            name='start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
