# Generated by Django 4.0.3 on 2022-05-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_membertopiclog_start_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertopiclog',
            name='stage',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='membertopiclog',
            name='step',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stage1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stage2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stage3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stage4',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
