# Generated by Django 4.0.4 on 2022-05-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_planflow_remove_memberplanmanage_plan_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.IntegerField(blank=True, max_length=3, null=True)),
                ('seq', models.IntegerField(blank=True, max_length=2, null=True)),
                ('stage', models.IntegerField(blank=True, max_length=1, null=True)),
                ('step', models.IntegerField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PlanFlow',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stage1',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stage2',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stage3',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='stage4',
        ),
    ]
