# Generated by Django 4.0.4 on 2022-05-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_delete_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.IntegerField(blank=True, max_length=3, null=True)),
                ('plan_name', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
