# Generated by Django 4.0.4 on 2022-05-30 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_value', '0010_delete_plan'),
        ('manager', '0014_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_value.step'),
        ),
    ]
