# Generated by Django 4.0.4 on 2022-05-30 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_plandetail_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='plan_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.plan'),
        ),
    ]
