# Generated by Django 4.0.4 on 2022-06-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_membertopiclog_stage_alter_membertopiclog_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='seq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
