# Generated by Django 4.0.4 on 2022-07-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_plan_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('visible', models.IntegerField(blank=True, default=1, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('memo', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
