# Generated by Django 4.0.4 on 2022-09-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_plandetail_step_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandetail',
            name='step_mobile',
        ),
    ]
